<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $time_stamp=now();
        $countries =
            [
                ['name'=>'المملكة العربية السعودية','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'إثيوبيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أذربيجان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أرمينيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أروبا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'إريتريا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أسبانيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أستراليا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'إستونيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'إسرائيل','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أفغانستان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'إقليم المحيط الهندي البريطاني','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'إكوادور','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الأرجنتين','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الأردن','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الإمارات العربية المتحدة','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'ألبانيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'البرازيل','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'البرتغال','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'البوسنة والهرسك','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الجابون','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الجزائر','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الدانمارك','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الرأس الأخضر','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'فلسطين','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'السلفادور','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'السنغال','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'السودان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'السويد','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الصومال','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الصين','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'العراق','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الفلبين','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الكاميرون','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الكونغو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الكونغو (جمهورية الكونغو الديمقراطية)','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الكويت','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'ألمانيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'المجر','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'المغرب','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'المكسيك','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'المملكة المتحدة','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'المناطق الفرنسية الجنوبية ومناطق انتراكتيكا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'النرويج','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'النمسا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'النيجر','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الهند','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الولايات المتحدة','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'اليابان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'اليمن','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'اليونان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أنتاركتيكا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أنتيغوا وبربودا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أندورا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'إندونيسيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أنغولا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أنغويلا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أوروجواي','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أوزبكستان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أوغندا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أوكرانيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'إيران','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أيرلندا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'أيسلندا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'إيطاليا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بابوا-غينيا الجديدة','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'باراجواي','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'باربادوس','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'باكستان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بالاو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'برمودا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بروناي','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بلجيكا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بلغاريا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بنجلاديش','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بنما','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بنين','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بوتان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بوتسوانا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بورتو ريكو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بوركينا فاسو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بوروندي','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بولندا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بوليفيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بولينزيا الفرنسية','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بيرو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بيلاروس','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'بيليز','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'تايلاند','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'تايوان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'تركمانستان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'تركيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'ترينيداد وتوباجو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'تشاد','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'تشيلي','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'تنزانيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'توجو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'توفالو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'توكيلاو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'تونجا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'تونس','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'تيمور الشرقية (تيمور الشرقية)','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جامايكا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جامبيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جبل طارق','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جرينلاند','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر الأنتيل الهولندية','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر البتكارين','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر البهاما','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر العذراء البريطانية','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر العذراء، الولايات المتحدة','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر القمر','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر الكوكوس (كيلين)','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر المالديف','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر تركس وكايكوس','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر ساموا الأمريكية','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر سولومون','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر فايرو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر فرعية تابعة للولايات المتحدة','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر فوكلاند (أيزلاس مالفيناس)','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر فيجي','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر كايمان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر كوك','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر مارشال','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزر ماريانا الشمالية','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزيرة الكريسماس','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزيرة بوفيه','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزيرة مان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزيرة نورفوك','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جزيرة هيرد وجزر ماكدونالد','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جمهورية أفريقيا الوسطى','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جمهورية التشيك','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جمهورية الدومينيكان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جنوب أفريقيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جواتيمالا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جواديلوب','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جوام','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جورجيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جورجيا الجنوبية وجزر ساندويتش الجنوبية','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جيانا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جيانا الفرنسية','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جيبوتي','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جيرسي','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جيرنزي','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'دولة الفاتيكان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'دومينيكا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'رواندا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'روسيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'رومانيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'ريونيون','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'زامبيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'زيمبابوي','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'ساموا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سان مارينو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سانت بيير وميكولون','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سانت فينسنت وجرينادينز','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سانت كيتس ونيفيس','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سانت لوشيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سانت هيلينا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'ساوتوماي وبرينسيبا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سفالبارد وجان ماين','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سلوفاكيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سلوفينيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سنغافورة','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سوازيلاند','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سوريا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سورينام','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سويسرا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سيراليون','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سيريلانكا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سيشل','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'صربيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'طاجيكستان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'عمان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'غانا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'غرينادا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'غينيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'غينيا الاستوائية','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'غينيا بيساو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'فانواتو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'فرنسا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'فنزويلا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'فنلندا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'فيتنام','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'قبرص','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'قطر','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'قيرقيزستان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'كازاخستان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'كاليدونيا الجديدة','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'كامبوديا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'كرواتيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'كندا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'كوبا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'كوت ديفوار (ساحل العاج)','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'كوريا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'كوريا الشمالية','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'كوستاريكا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'كولومبيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'كيريباتي','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'كينيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'لاتفيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'لاوس','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'لبنان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'لختنشتاين','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'لوكسمبورج','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'ليبيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'ليبيريا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'ليتوانيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'ليسوتو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'مارتينيك','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'ماكاو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'ماكرونيزيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'مالاوي','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'مالطا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'مالي','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'ماليزيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'مايوت','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'مدغشقر','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'مصر','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'مقدونيا، جمهورية يوغوسلافيا السابقة','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'مملكة البحرين','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'منغوليا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'موريتانيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'موريشيوس','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'موزمبيق','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'مولدوفا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'موناكو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'مونتسيرات','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'مونتينيغرو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'ميانمار','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'ناميبيا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'ناورو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'نيبال','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'نيجيريا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'نيكاراجوا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'نيوا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'نيوزيلندا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'هايتي','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'هندوراس','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'هولندا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'هونغ كونغ SAR','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'واليس وفوتونا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'اسلاند','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'كوسوفو','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'واليس وفوتونا','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'الصحراء الغربية','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'المملكة المتحدة','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'تيمور الشرقية','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'جنوب السودان','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سانت بارتيليمي','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
                ['name'=>'سانت مارتن','created_at'=>$time_stamp,'updated_at'=>$time_stamp],
            ];
               foreach (array_chunk($countries, 100) as $chunk_data_val) {
                DB::table('countries')->insert($chunk_data_val);
              }

    }
}
